export const CART_ACTION_TYPES = {
    TOGGLE_CART_VIEW: "TOGGLE_CART_VIEW",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    REMOVE_ITEM_CHECKOUT: "REMOVE_ITEM_CHECKOUT",
    CLEAR_CART: "CLEAR_CART"
}